# Computers that are available on our site.
netbook:
  name: 'ASUS Chromebook 13-Inch with Gigabit WiFi, 16GB Storage & 2GB RAM'
  desc: 'The new line-up of sleek and ultra-portable ASUS Chromebooks features a spacious touchpad which gives easy control over multi-touch gesture inputs. With up to 11 hours of battery life, enjoy Chromebook all day while out and about or on the move.'
  cost: 194.00
  brand: 'Asus'
  series: 'Chromebook'
  model: 'C300MA-DB01'
  os: 'Chrome OS'
  processor: 'Intel Celeron 2.16GHz'
  battery: 'Up to 10 hours'
  memory: '2GB'
  storage: '16GB SSD'
  screen: '11.6 inches (1366x768)'
  wifi: '802.11 A/C'
  weight: '2.5 pounds'
  dimensions: '12 x 7.90 x 0.80 inches'
  release_date: '2014-05-06'

laptop:
  name: 'HP Stream 14 Quad Core Laptop with Beats Audio '
  desc: 'Get the job done with this innovative cloud-connected Windows PC. Store your content in the cloud for easy access from anywhere you have Internet.'
  cost: 275.00
  brand: 'HP'
  series: 'HP Stream'
  model: 'J9V55UA#ABA'
  os: 'Windows 8.1'
  processor: '1 GHz AMD A Series'
  battery: '6.5 hours'
  memory: '2GB'
  storage: '32GB'
  screen: '14 inches (1366 x 768)'
  wifi: '802.11bgn'
  weight: '3.9 pounds'
  dimensions: '9.45 x 13.54 x 0.70 inches'
  release_date: 'September 7, 2014'

macbook:
  name: 'Apple MacBook Pro MGXC2LL/A 15.4-Inch Laptop with Retina Display'
  desc: "Retina Display The 15‑inch model has over 5 million pixels so you can retouch your photos or edit a home movie in HD and experience an astounding level of clarity. Text is razor sharp, too, so even everyday things like browsing the web and revising a document are better than ever. It's a display worthy of world's most advanced notebook. Intel Core i7 Fourth-generation Intel Core i7 processors help you power through even the most complicated technical computing tasks."
  cost: 2,249.99
  brand: 'Apple'
  series: 'MacBook Pro'
  model: 'MGXC2LL/A'
  os: 'OS X Mavericks'
  processor: '2.5 GHz Intel Core i7'
  battery: '5.5 hours'
  memory: '16GB'
  storage: '512GB'
  screen: '15.4 inches (2880 x 1800)'
  wifi: '802.11bgn'
  weight: '4.5 pounds'
  dimensions: '9.73 x 14.13 x 0.71 inches'
  release_date: '2014-07-29'

desktop:
  name: 'HP 110-430 Desktop w/HP W2371d 23-Inch Screen LED-lit Monitor'
  desc: 'HP 110-430 PC sticks to the basics, providing the competitive performance and familiar, essential features you routinely need at an economical price. Approachable design: The HP 110 has been designed with a clean, modern style. Trustworthy and straightforward: The HP 110 provides reliable performance for everyday computing. '
  cost: 257.95
  brand: 'HP'
  series: 'PC Desktop'
  model: 'J4W31AA#ABA'
  os: 'Windows 8'
  processor: '2.41 GHz Intel Celeron'
  battery: 'N/A'
  memory: '4GB'
  storage: '500GB'
  screen: '20 inches (1600 x 900)'
  wifi: '802.11gn'
  weight: '11.9 pounds'
  dimensions: '15.14 x 6.50 x 14.33 inches'
  release_date: '2014-09-09'

imac:
  name: 'Apple iMac ME086LL/A 21.5-Inch Desktop'
  desc: 'The stunning all-in-one iMac features a beautiful 21.5 widescreen display. Fourth-generation quad-core Intel Core processors and superfast NVIDIA graphics make it the most powerful iMac yet.'
  cost: 1279.00
  brand: 'Apple'
  series: 'iMac'
  model: 'ME086LL/A'
  os: 'OS X Moutain Lion'
  processor: '2.7 GHz Intel Core i5'
  battery: 'N/A'
  memory: '8 GB SDRAM'
  storage: '1TB'
  screen: '21.5 inches (1920 x 1080)'
  wifi: '802.11ac'
  weight: '12.5 pounds'
  dimensions: '20.80 x 6.90 x 17.70 inches'
  release_date: '2013-09-24'
