common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: ec2-23-21-219-209.compute-1.amazonaws.com
  database: dfb4k5vu5fumc3
  username: huvionhigzqkun
  password: _b6Dj2JU8YZUJbDg9z680e8fEq

development:
  <<: *common

test:
  <<: *common
  host: localhost
  database: fundme-test
  username: fundme
  password: funds!

production:
  <<: *common