common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: ec2-23-23-80-55.compute-1.amazonaws.com
  database: dchgkis110gnm7
  username: vcmejdqfieqwyt
  password: u-yj8CEPbWSSDCDVBDlZECnZNP

development:
  <<: *common

test:
  <<: *common
  host: localhost
  database: fundme-test
  username: fundme
  password: funds!

production:
  <<: *common