common: &common
  adapter: postgresql
  encoding: unicode
#  adapter: mysql2
#  encoding: utf8
  pool: 5
  host: localhost
  username: fundme
  password: funds!

development:
  <<: *common
  database: fundme-dev

profile:
  <<: *common
  database: grh-dev

test:
  <<: *common
  database: fundme-test

production:
  <<: *common
  database: fundme
  socket: /var/run/mysqld/mysqld.sock
